### PR TITLE
Minor change to the Windows Powershell Command for client installation

### PR DESCRIPTION
**Pull request by JustinHenderson88**
## Description

the "-" in front of the "Add" command should be excluded when running this command as admin (in Powershell) in Windows 10. The "-" causes this command to be ignored.
## Motivation and Context

Causes automatic installation of Windows client command to fail in Windows 10. 

## How Has This Been Tested?

This has been verified in Windows 10 ONLY. I have **not** tested in other Windows OS

Verified on 2 PCs running Windows 10 and Parallels VM installed with Windows 10

## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [] I have read the **CONTRIBUTING** document.
- [] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
-Unsure about this question? Your documentation or mine?
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by TC1977** [comment]
This commit doesn’t do what it says it does?

**Comment by davidemyers** [comment]
It looks like the PR was submitted from `trailofbits/algo/readme-update` instead of `JustinHenderson88/algo/patch-1`. It might be easiest just to close this one and submit a new one.

**Comment by JustinHenderson88** [comment]
@davidemyers Do I need to redo this since it was apparently commited in the wrong place?

**Comment by davidemyers** [comment]
I think a new PR would be easiest (but I'm not a git guru). Go to your fork and switch to the branch where you made the commit. Then submit the PR from there.

**Comment by jackivanov** [comment]
Send a new PR, please.

**Pull request closed without merging**
