### PR TITLE
Facts definition fix

### LINKED ISSUE #1409: Installation error after #1397
**Describe the bug**

If `ipsec_enabled` is set to `false` in `config.cfg`, then the install crashes with the error "The task includes an option with an undefined variable."

The script runs fine if `ipsec_enabled` is set to `true`.

**To Reproduce**

1. Set `ipsec_enabled` to `false`
2. Run `./algo`

**Expected behavior**

The script runs as normal, but omits Strongswan.

**Additional context**

**Full log**

```
*****s-MacBook-Pro:algo-master *****$ cd ~/Downloads/algo-master
*****s-MacBook-Pro:algo-master *****$ nano config.cfg
*****s-MacBook-Pro:algo-master *****$ python -m virtualenv --python=`which python2` env &&
>     source env/bin/activate &&
>     python -m pip install -U pip virtualenv &&
>     python -m pip install -r requirements.txt
New python executable in /Users/*****/Downloads/algo-master/env/bin/python
Installing setuptools, pip, wheel...
done.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages (19.1)
Collecting virtualenv
  Using cached https://files.pythonhosted.org/packages/4f/ba/6f9315180501d5ac3e707f19fcb1764c26cc6a9a31af05778f7c2383eadb/virtualenv-16.5.0-py2.py3-none-any.whl
Installing collected packages: virtualenv
Successfully installed virtualenv-16.5.0
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting ansible==2.7.10 (from -r requirements.txt (line 1))
Requirement already satisfied: setuptools in ./env/lib/python2.7/site-packages (from ansible==2.7.10->-r requirements.txt (line 1)) (41.0.1)
Collecting paramiko (from ansible==2.7.10->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfdba20114fa947d7ba6eb68a2e452d89b920e62227/paramiko-2.4.2-py2.py3-none-any.whl
Collecting jinja2 (from ansible==2.7.10->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Collecting cryptography (from ansible==2.7.10->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/f5/2a/48848dd65908190d68ef389ad8ee9d0010278f7a9118f40d8fed7d84a326/cryptography-2.6.1-cp27-cp27m-macosx_10_6_intel.whl
Collecting PyYAML (from ansible==2.7.10->-r requirements.txt (line 1))
Collecting pyasn1>=0.1.7 (from paramiko->ansible==2.7.10->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl
Collecting bcrypt>=3.1.3 (from paramiko->ansible==2.7.10->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/14/1b/f6f05b80783ff84c58bca5f2b7a4cef7c02570e4bb2e40d326abb2ba41d3/bcrypt-3.1.6-cp27-cp27m-macosx_10_6_intel.whl
Collecting pynacl>=1.0.1 (from paramiko->ansible==2.7.10->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/51/83/2db5b919bf9848fe25d301225a16faabc378419e7eaf00da0b7d200fe801/PyNaCl-1.3.0-cp27-cp27m-macosx_10_6_intel.whl
Collecting MarkupSafe>=0.23 (from jinja2->ansible==2.7.10->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/6d/d2/0ccd2c0e2cd93b35e765d9b3205cd6602e6b202b522fc7997531353715b3/MarkupSafe-1.1.1-cp27-cp27m-macosx_10_6_intel.whl
Collecting enum34; python_version < "3" (from cryptography->ansible==2.7.10->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography->ansible==2.7.10->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/16/f6/46a3dece43541b2cbf3776ec2299e370a2408d9380958401cacb6d101853/cffi-1.12.3-cp27-cp27m-macosx_10_6_intel.whl
Collecting six>=1.4.1 (from cryptography->ansible==2.7.10->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography->ansible==2.7.10->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting ipaddress; python_version < "3" (from cryptography->ansible==2.7.10->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography->ansible==2.7.10->-r requirements.txt (line 1))
Installing collected packages: pyasn1, six, pycparser, cffi, bcrypt, enum34, asn1crypto, ipaddress, cryptography, pynacl, paramiko, MarkupSafe, jinja2, PyYAML, ansible
Successfully installed MarkupSafe-1.1.1 PyYAML-5.1 ansible-2.7.10 asn1crypto-0.24.0 bcrypt-3.1.6 cffi-1.12.3 cryptography-2.6.1 enum34-1.1.6 ipaddress-1.0.22 jinja2-2.10.1 paramiko-2.4.2 pyasn1-0.4.5 pycparser-2.19 pynacl-1.3.0 six-1.12.0
(env) *****s-MacBook-Pro:algo-master *****$ ./algo

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Verify Ansible meets Drupal VM's version requirements.] ******************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

PLAY [Ask user for the input] **************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]
[Region prompt]
What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Vultr
    5. Microsoft Azure
    6. Google Compute Engine
    7. Scaleway
    8. OpenStack (DreamCompute optimised)
    9. Install to existing Ubuntu 18.04 server (Advanced)
  
Enter the number of your desired provider
:

TASK [Region prompt] ***********************************************************
ok: [localhost]

TASK [Set facts based on the input] ********************************************
ok: [localhost]
[VPN server name prompt]
Name the vpn server
[algo]
:

TASK [VPN server name prompt] **************************************************
ok: [localhost]
[DNS adblocking prompt]
Do you want to install an ad blocking DNS resolver on this VPN server?
[y/N]
:

TASK [DNS adblocking prompt] ***************************************************
ok: [localhost]
[SSH tunneling prompt]
Do you want each user to have their own account for SSH tunneling?
[y/N]
:

TASK [SSH tunneling prompt] ****************************************************
ok: [localhost]

TASK [Set facts based on the input] ********************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'user_input'\n\nThe error appears to have been in '/Users/*****/Downloads/algo-master/input.yml': line 115, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n      - name: Set facts based on the input\n        ^ here\n"}
included: /Users/*****/Downloads/algo-master/playbooks/rescue.yml for localhost

TASK [debug] *******************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] ***************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=10   changed=0    unreachable=0    failed=2 
```

### PR DESCRIPTION
**Pull request by jackivanov**
## Description
Fact `algo_store_cakey` shouldn't be handled if `ipsec_enabled: false`
Variable `ansible_ssh_user` shouldn't be handled if deploying to localhost

## Motivation and Context
Fixes #1409

## How Has This Been Tested?
Deployed locally and to Vultr

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by TC1977** [comment]
Still failed after switching to `fix-1409` branch.
```

TASK [Set facts based on the input] ************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'user_input'\n\nThe error appears to have been in '/Users/********/Downloads/algo/input.yml': line 115, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n      - name: Set facts based on the input\n        ^ here\n"}
```

**Comment by jackivanov** [comment]
@TC1977 Could you send the whole log, please? I was trying to reproduce it with simplest use-cases, but couldn't catch the error

**Comment by TC1977** [comment]
I'll try setting it up in a new working directory and re-running.

```
(env) ************:algo ********$ ansible --version
ansible 2.7.10
  config file = /Users/********/Downloads/algo/ansible.cfg
  configured module search path = [u'/Users/********/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/********/Downloads/algo/env/lib/python2.7/site-packages/ansible
  executable location = /Users/********/Downloads/algo/env/bin/ansible
  python version = 2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
(env) ************:algo ********$ nano config.cfg
(env) ************:algo ********$ ./algo

PLAY [localhost] *******************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************
ok: [localhost]

TASK [Verify Ansible meets Drupal VM's version requirements.] **********************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

PLAY [Ask user for the input] ******************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************
ok: [localhost]
[Region prompt]
What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Vultr
    5. Microsoft Azure
    6. Google Compute Engine
    7. Scaleway
    8. OpenStack (DreamCompute optimised)
    9. Install to existing Ubuntu 18.04 server (Advanced)
  
Enter the number of your desired provider
:

TASK [Region prompt] ***************************************************************************************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] ************************************************************************************************************************************************
ok: [localhost]
[VPN server name prompt]
Name the vpn server
[algo]
:

TASK [VPN server name prompt] ******************************************************************************************************************************************************
ok: [localhost]
[DNS adblocking prompt]
Do you want to install an ad blocking DNS resolver on this VPN server?
[y/N]
:

TASK [DNS adblocking prompt] *******************************************************************************************************************************************************
ok: [localhost]
[SSH tunneling prompt]
Do you want each user to have their own account for SSH tunneling?
[y/N]
:

TASK [SSH tunneling prompt] ********************************************************************************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] ************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'user_input'\n\nThe error appears to have been in '/Users/********/Downloads/algo/input.yml': line 115, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n      - name: Set facts based on the input\n        ^ here\n"}
included: /Users/********/Downloads/algo/playbooks/rescue.yml for localhost

TASK [debug] ***********************************************************************************************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] *******************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *************************************************************************************************************************************************************************
localhost                  : ok=10   changed=0    unreachable=0    failed=2   
```

**Comment by TC1977** [comment]
Yep, still fails in new working directory. Same error.

**Comment by TC1977** [comment]
Got a little bit farther, but now it's throwing an error with the algo_windows.
```
***********:algo2 ********$ source env/bin/activate
(env) ************:algo2 ********$ nano config.cfg
(env) ************:algo2 ********$ grep "ipsec_enabled" config.cfg
ipsec_enabled: false
(env) ************:algo2 ********$ ./algo

PLAY [localhost] *******************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************
ok: [localhost]

TASK [Verify Ansible meets Drupal VM's version requirements.] **********************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

PLAY [Ask user for the input] ******************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************
ok: [localhost]
[Cloud prompt]
What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Vultr
    5. Microsoft Azure
    6. Google Compute Engine
    7. Scaleway
    8. OpenStack (DreamCompute optimised)
    9. Install to existing Ubuntu 18.04 server (Advanced)
  
Enter the number of your desired provider
:

TASK [Cloud prompt] ****************************************************************************************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] ************************************************************************************************************************************************
ok: [localhost]
[VPN server name prompt]
Name the vpn server
[algo]
:

TASK [VPN server name prompt] ******************************************************************************************************************************************************
ok: [localhost]
[DNS adblocking prompt]
Do you want to install an ad blocking DNS resolver on this VPN server?
[y/N]
:

TASK [DNS adblocking prompt] *******************************************************************************************************************************************************
ok: [localhost]
[SSH tunneling prompt]
Do you want each user to have their own account for SSH tunneling?
[y/N]
:

TASK [SSH tunneling prompt] ********************************************************************************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] ************************************************************************************************************************************************
ok: [localhost]

PLAY [Provision the server] ********************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************
ok: [localhost]

--> Please include the following block of text when reporting issues:

Algo running on: Mac OS X 10.14.4
Created from git fork. Last commit: 6b67fad separate ipsec related facts
Python 2.7.15
Runtime variables:
    algo_provider "vultr"
    algo_local_dns "True"
    algo_ssh_tunneling "False"
    wireguard_enabled "True"
    dns_encryption "True"

TASK [Display the invocation environment] ******************************************************************************************************************************************
changed: [localhost -> localhost]

TASK [Install the requirements] ****************************************************************************************************************************************************
changed: [localhost -> localhost]

TASK [Generate the SSH private key] ************************************************************************************************************************************************
changed: [localhost]

TASK [Generate the SSH public key] *************************************************************************************************************************************************
changed: [localhost]
[cloud-vultr : pause]
Enter the local path to your configuration INI file
(https://trailofbits.github.io/algo/cloud-vultr.html):
:

TASK [cloud-vultr : pause] *********************************************************************************************************************************************************
ok: [localhost]

TASK [cloud-vultr : Set the token as a fact] ***************************************************************************************************************************************
ok: [localhost]

TASK [cloud-vultr : Get regions] ***************************************************************************************************************************************************
ok: [localhost]

TASK [cloud-vultr : Format regions] ************************************************************************************************************************************************
ok: [localhost]

TASK [cloud-vultr : Set regions as a fact] *****************************************************************************************************************************************
ok: [localhost]

TASK [cloud-vultr : Set default region] ********************************************************************************************************************************************
ok: [localhost]
[cloud-vultr : pause]
What region should the server be located in?
(https://www.vultr.com/locations/):
    1.   Sydney
    2.   Toronto
    3.   Frankfurt
    4.   Paris
    5.   London
    6.   Tokyo
    7.   Amsterdam
    8.   Singapore
    9.   Miami
    10.   Silicon Valley
    11.   New Jersey
    12.   Dallas
    13.   Chicago
    14.   Los Angeles
    15.   Seattle
    16.   Atlanta
  
Enter the number of your desired region
[11]
:

TASK [cloud-vultr : pause] *********************************************************************************************************************************************************
ok: [localhost]

TASK [cloud-vultr : Set the desired region as a fact] ******************************************************************************************************************************
ok: [localhost]

TASK [cloud-vultr : Upload the SSH key] ********************************************************************************************************************************************
changed: [localhost]

TASK [cloud-vultr : Creating a firewall group] *************************************************************************************************************************************
ok: [localhost]

TASK [cloud-vultr : Creating firewall rules] ***************************************************************************************************************************************
changed: [localhost] => (item={u'ip': u'v4', u'cidr': u'0.0.0.0/0', u'protocol': u'tcp', u'port': 22})
changed: [localhost] => (item={u'ip': u'v6', u'cidr': u'::/0', u'protocol': u'tcp', u'port': 22})
changed: [localhost] => (item={u'ip': u'v4', u'cidr': u'0.0.0.0/0', u'protocol': u'udp', u'port': 500})
changed: [localhost] => (item={u'ip': u'v6', u'cidr': u'::/0', u'protocol': u'udp', u'port': 500})
changed: [localhost] => (item={u'ip': u'v4', u'cidr': u'0.0.0.0/0', u'protocol': u'udp', u'port': 4500})
changed: [localhost] => (item={u'ip': u'v6', u'cidr': u'::/0', u'protocol': u'udp', u'port': 4500})
changed: [localhost] => (item={u'ip': u'v4', u'cidr': u'0.0.0.0/0', u'protocol': u'udp', u'port': 51820})
changed: [localhost] => (item={u'ip': u'v6', u'cidr': u'::/0', u'protocol': u'udp', u'port': 51820})

TASK [cloud-vultr : Creating a server] *********************************************************************************************************************************************
changed: [localhost]

TASK [cloud-vultr : set_fact] ******************************************************************************************************************************************************
ok: [localhost]

TASK [Set subjectAltName as afact] *************************************************************************************************************************************************
ok: [localhost]

TASK [Add the server to an inventory group] ****************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'algo_windows' is undefined\n\nThe error appears to have been in '/Users/********/Downloads/algo2/playbooks/cloud-post.yml': line 6, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add the server to an inventory group\n  ^ here\n"}
included: /Users/********/Downloads/algo2/playbooks/rescue.yml for localhost

TASK [debug] ***********************************************************************************************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] *******************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *************************************************************************************************************************************************************************
localhost                  : ok=30   changed=7    unreachable=0    failed=2   
```

**Comment by TC1977** [comment]
Cloud deploy onto Vultr with `ipsec_enabled: false` was successful.

Local install onto Vultr instance running Ubuntu 18.04 was also successful.

Local install onto Vultr instance running Ubuntu 18.04, _with_ `ipsec_enabled: false` also successful.

**Comment by TC1977** [comment]
I can reproduce the error that @marcovn reported, by creating a Vultr Ubuntu 18.04.2 LTS instance, `git checkout fix-1409`, then proceeding to successfully run `./algo`, then adding two users and running `./algo update-users -vvv`:

```ssh
(env) root@LocalAlgoTest:~/algo# ./algo update-users -vvv
ansible-playbook 2.7.10
  config file = /root/algo/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/algo/env/local/lib/python2.7/site-packages/ansible
  executable location = /root/algo/env/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
Using /root/algo/ansible.cfg as config file
/root/algo/inventory did not meet host_list requirements, check plugin documentation if this is unexpected
/root/algo/inventory did not meet script requirements, check plugin documentation if this is unexpected
Parsed /root/algo/inventory inventory source with ini plugin
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
statically imported: /root/algo/playbooks/cloud-pre.yml
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
statically imported: /root/algo/roles/wireguard/tasks/keys.yml
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
statically imported: /root/algo/roles/strongswan/tasks/ipsec_configuration.yml
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
statically imported: /root/algo/roles/strongswan/tasks/openssl.yml
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
statically imported: /root/algo/roles/strongswan/tasks/distribute_keys.yml
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
Read vars_file 'configs/{{ inventory_hostname }}/.config.yml'
statically imported: /root/algo/roles/strongswan/tasks/client_configs.yml
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable
Read vars_file 'config.cfg'
skipping vars_file 'configs/{{ inventory_hostname }}/.config.yml' due to an undefined variable

PLAYBOOK: users.yml **********************************************************************************************************************************************
2 plays in users.yml
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'

PLAY [localhost] *************************************************************************************************************************************************
META: ran handlers
Read vars_file 'config.cfg'
[Server address prompt]
Enter the IP address of your server: (or use localhost for local installation):

TASK [Server address prompt] *************************************************************************************************************************************
task path: /root/algo/users.yml:10
ok: [localhost] => {
    "changed": false, 
    "delta": 2, 
    "echo": true, 
    "rc": 0, 
    "start": "2019-05-01 01:51:47.643318", 
    "stderr": "", 
    "stdout": "Paused for 0.04 minutes", 
    "stop": "2019-05-01 01:51:50.173436", 
    "user_input": ""
}
Read vars_file 'config.cfg'

TASK [Set facts based on the input] ******************************************************************************************************************************
task path: /root/algo/users.yml:16
ok: [localhost] => {
    "ansible_facts": {
        "algo_server": "omit"
    }, 
    "changed": false
}
Read vars_file 'config.cfg'

TASK [Import host specific variables] ****************************************************************************************************************************
task path: /root/algo/users.yml:23
fatal: [localhost]: FAILED! => {
    "ansible_facts": {}, 
    "ansible_included_var_files": [], 
    "changed": false, 
    "message": "Could not find or access 'configs/omit/.config.yml'\nSearched in:\n\t/root/algo/vars/configs/omit/.config.yml\n\t/root/algo/configs/omit/.config.yml\n\t/root/algo/vars/configs/omit/.config.yml\n\t/root/algo/configs/omit/.config.yml on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
}
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
included: /root/algo/playbooks/rescue.yml for localhost
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'

TASK [debug] *****************************************************************************************************************************************************
task path: /root/algo/playbooks/rescue.yml:2
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}
Read vars_file 'config.cfg'

TASK [Fail the installation] *************************************************************************************************************************************
task path: /root/algo/playbooks/rescue.yml:5
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "msg": "Failed as requested from task"
}

PLAY RECAP *******************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=2   
```

**Comment by gyalworkstation** [comment]
image

**Pull request merged**
