### PR TITLE
Add new Azure regions and allow user to select VM size

### PR DESCRIPTION
**Pull request by joshmeisels**
- Added a bunch of additional Azure regions
- Added a prompt to let the user choose VM size between 3 options, including 2 super low cost ones.
- Removed the default VM size of D1 which is being phased out, replaced with D1v2.

Future enhancements could include:
- Asking for a continent before the Azure region - this way it isn't such a long list to choose from.
- Auto-pulling of Azure regions as described in https://github.com/trailofbits/algo/issues/291

### CODE REVIEW

**Comment by dguido** [comment]
Thanks for this PR! Can you remove the bits about selecting a VM size? I'd like to move any configuration of VM size into the config.cfg file to avoid prompting users about it. Then, advanced users can dig into the config file to edit it if necessary. The default size should work for 99% of all use cases. Each new question we add to the initial script adds to the complexity for regular users.

**Comment by joshmeisels** [comment]
@dguido sure, I'll remove that part. Should the default size be `Standard_D1v2` or `Basic_A0`?

Per my post on Slack, D1v2 is way more expensive, but the performance suffers on Basic_A0. I assume it should default to the more expensive size with better perf.

**Comment by dguido** [comment]
Ah, you assume wrong! A0 is more in line with our philosophy of using the least resources that will suffice. Our user base is also cost sensitive.

**Comment by joshmeisels** [comment]
Thanks @dguido. I've undone the change to let the user select a VM size and changed the hard coded value to the cheapest one.

**Comment by dguido** [comment]
Thanks!

**Pull request merged**
