### PR TITLE
Let users choose the distro version

### PR DESCRIPTION
**Pull request by gunph1ld**
DO, AWS, GCE have ubuntu 17, but Azure still not

### CODE REVIEW

**Comment by gunph1ld** [comment]
Fixes #449

**Comment by dguido** [comment]
FYI the DNS Ad blocking breaks on 17.04 because of systemd haha

```
RUNNING HANDLER [dns_adblocking : restart dnsmasq] *****************************
fatal: [104.236.200.178]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service dnsmasq: Warning: dnsmasq.service changed on disk. Run 'systemctl daemon-reload' to reload units.\nJob for dnsmasq.service failed because the control process exited with error code.\nSee \"systemctl status dnsmasq.service\" and \"journalctl -xe\" for details.\n"}
```

**Comment by jplock** [comment]
To fix it, I had to remove `/etc/dnsmasq.d/lxd` it was a symlink to no where for me

**Comment by dguido** [comment]
Is there a patch we should make to that role so it works on both 16.04 and 17.04?

**Comment by dguido** [comment]
Other than the adblocking role, it looks like all the other roles work perfect.

**Comment by gunph1ld** [comment]
I've fixed the apparmor profile

**Comment by dguido** [comment]
Nice! This is going to make it really easy to fully migrate to 17.04 when we want to.

**Pull request merged**
