### PR TITLE
Generate mobileconfigs for WireGuard

### LINKED ISSUE #1517: support generating of iOS profiles (.mobileconfig) for WireGuard
**Is your feature request related to a problem? Please describe.**
As stated in [Installing WireGuard tunnels using Configuration Profiles](https://github.com/WireGuard/wireguard-apple/blob/master/MOBILECONFIG.md) WireGuard also supports Apple Profiles (.mobileconfig).

**Describe the solution you'd like**
Algo should also generate .mobileconfig for WireGuard. This would make profile distribution (eg. via Enterprise Mobile Devicemanagement) possible and easy.

Thanks for the good work!

### PR DESCRIPTION
**Pull request by jackivanov**
## Description
- Generate profiles to set up tunnels on Apple devices 
- This PR brings onDemand for WireGuard via apple profiles.

## Motivation and Context
Closes #1517

## How Has This Been Tested?
Installed to MacOS and iPhone

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by TC1977** [comment]
Will this PR mean that installing the WireGuard app is no longer required?

**Comment by jackivanov** [comment]
No, we still need the app. This PR brings onDemand for WireGuard via apple profiles.

**Comment by TC1977** [comment]
In that case, is it time to drop the "IPsec" from [here](https://github.com/trailofbits/algo/blob/master/input.yml#L59) and [here](https://github.com/trailofbits/algo/blob/master/input.yml#L67)?

**Comment by jackivanov** [comment]
@TC1977 Nice catch! I'll fix it

**Comment by boschkundendienst** [comment]
Thank you very much!

**Pull request merged**
