### PR TITLE
EC2

### PR DESCRIPTION
**Pull request by defunctio**
EC2 Support

### CODE REVIEW

**Comment by dguido** [comment]
Hey @gunph1ld, can you review this PR and provide some feedback?

**Comment by defunctio** [comment]
This PR also includes fixes for #32 that may conflict with that merge.

**Comment by dguido** [comment]
I hate to be a pain, but can you rebase it?

**Comment by defunctio** [comment]
rebased, awaiting testing and review. Has not been tested on DO

**Comment by gunph1ld** [comment]
Good, thanks. Seems, we need to move up using roles now

**Comment by defunctio** [comment]
@gunph1ld Agree'd

**Pull request merged**
