### PR TITLE
Update cloud-azure.md with performance recs

### PR DESCRIPTION
**Pull request by im-batman**
## Description
Change to Azure docs to add performance recommendations.

## Motivation and Context
The Basic_A0 instance was limiting me to 8 Mbps on multiple platforms. I got frustrated and tried Standard_A0. That did the trick, and it's not much more expensie.

## How Has This Been Tested?
I tried several Basic_A0 roll-outs in several regions and ran the Google speed test. They all came back the same: 8 Mbps (I'm on a 100 Mbps carrier connection). I rolled out a Standard_A0 instance and got throughput upwards of 90 Mbps. Huzzah!

## Types of changes
- [x] Document update. Provided recommendation to use Standard_A0 if Basic_A0 is too slow.

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by TC1977** [comment]
Reviewing the Microsoft [Azure pricing chart for Linux instances](https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/), the Standard_B1S or B1LS instance both appear to be cheaper than either Standard_A0 or Basic_A0, and perhaps comparable to the AWS T2.micro, which worked great for me. And Azure's [free tier offer](https://azure.microsoft.com/en-us/free/) includes 750 hours of a B1S per month for a year. But I don't see expected bandwidth stats listed [with the other instance stats](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general#b-series). 

Care to try the bandwidth for one of those instances and report back? I did find that the Standard_A0 is [expected to have bandwidth of around 100Mbps](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-previous-gen#a-series), give or take 15%.

**Comment by im-batman** [comment]
> Care to test the bandwidth for one of those instances and report back? I did find that the Standard_A0 is [expected to have bandwidth of around 100Mbps](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-previous-gen#a-series), give or take 15%.

Definitely, good catch. I didn't notice the Bxx builds were cheaper. I'll kick them off and report back.

**Comment by im-batman** [comment]
B1LS kept dying in different phases during deployment (dist-upgrade, etc), which leads me to believe it had too little RAM. B1S works like a champ, 90/90 on a 100/100 carrier.

**Comment by im-batman** [comment]
Discovered that `Standard_B1S` is both cheaper and faster than `Basic_A0`, so I'm recommending a change to the base config vs. documentation.
Ref: #1473

**Comment by jackivanov** [comment]
@im-batman Could you send a new PR, please?

**Comment by im-batman** [comment]
@jackivanov #1474

**Pull request closed without merging**
