### PR TITLE
Fixes for #491 - Naming in mobileconfig, powershell, and AWS EC2

### PR DESCRIPTION
**Pull request by bkono**
Normalized the various cloud_server_name entries to just
algo_server_name. Integrated algo_server_name into the mobileconfig
template as well as powershell. If a default name is provided, the 
original behavior of IP_subject_alt_name will be used to avoid conflicts. 
Also updated the Name tag in the cloudformation template to utilize the 
StackName (which is based on the algo_server_name).

### CODE REVIEW

**Comment by bkono** [comment]
Screenshots for confirmation of changes:

EC2 with non-default vpn server


EC2 instance name


.mobileconfig profile name


Apple VPN name in networks panel


Powershell $VpnName

**Comment by jackivanov** [comment]
A lot of changes are coming in [ansible2.5](https://github.com/trailofbits/algo/tree/ansible2.5).
And normalising variables as well. So, I don't actually see any reasons to merge it now, it will be rewritten anyway

**Comment by bkono** [comment]
> A lot of changes are coming in ansible2.5.
> And normalising variables as well. So, I don't actually see any reasons to merge it now, it will be rewritten anyway

@jackivanov That's fair; didn't know about the state of that branch when sending a PR was mentioned in issue #491. In this pass, the normalizing of variables was only to make the actual changes easier, specifically the mobileconfig/ps1/cloudformation template changes. Would be more than happy to drop that part. Glancing at the ansible2.5 branch, it doesn't look like any similar updates have been made yet. Is that far enough along that I could apply the actual (non variable naming) changes to it?

**Comment by jackivanov** [comment]
Yes, you could send a PR to [ansible2.5](https://github.com/trailofbits/algo/tree/ansible2.5)

**Comment by TC1977** [comment]
@bkono Time to set this up again?

**Comment by bkono** [comment]
@TC1977 Yep :) I'll take a stab this weekend.

**Pull request closed without merging**
