### PR TITLE
Fixes #199 Document how to pass on demand VPN for WiFi and Cellular to ansible-playbook

### LINKED ISSUE #199: Advanced installs can't configure VPN always-on functionality
The code provided in `deploy.yml` and described in the ADVANCED.md file:

https://github.com/trailofbits/algo/blob/master/docs/ADVANCED.md#scripted-deployment

does not seem to provide an equivalent to the interactive `algo` script to allow specifying that you want the VPN to be configured always on when on a cellular or wifi network.

### PR DESCRIPTION
**Pull request by grempe**

### CODE REVIEW

**Comment by dguido** [comment]
This is from a bug in the project, not a mistake in the documentation.

**Comment by grempe** [comment]
Sorry, you asked for a PR to improve the documentation in the ADVANCED.md, and yet you closed the PR, without merging, where I added improvements to the docs? Including documenting how to enable on-demand VPN for wifi/cellular and a (temporary) workaround for the SSH key bug?

Ugh.

**Comment by grempe** [comment]
https://github.com/trailofbits/algo/issues/191#issuecomment-269844028

**Comment by grempe** [comment]
Yes, I agree that that bugs should not be papered over with docs. However, there are changes in this PR which improves the documentation (IMHO). By closing it you seem to be saying that all of it is of no use? 

Specifically this doc PR has the following doc changes:

* Describes generally what scripted installation is good for: https://github.com/trailofbits/algo/pull/203/commits/c5b4da1692abc147a889536ba36a7f1e3dbf1762#diff-301b442ddc713ca888197dfd9ebc891cR35
* Demonstrates how to accomplish WiFi/Cellular on demand w/ an example: https://github.com/trailofbits/algo/pull/203/commits/c5b4da1692abc147a889536ba36a7f1e3dbf1762#diff-301b442ddc713ca888197dfd9ebc891cR43
* Provides a workaround for an existing issue (to be removed when the associated bug is resolved): https://github.com/trailofbits/algo/pull/203/commits/c5b4da1692abc147a889536ba36a7f1e3dbf1762#diff-301b442ddc713ca888197dfd9ebc891cR46
* Describes the `-t` TAGS option and how you might choose options for it: https://github.com/trailofbits/algo/pull/203/commits/c5b4da1692abc147a889536ba36a7f1e3dbf1762#diff-301b442ddc713ca888197dfd9ebc891cR59
* Describes how variables are provided with the `-e` option and documents the WiFi/Cellular options. Is this not an appropriate way to accomplish this?: https://github.com/trailofbits/algo/pull/203/commits/c5b4da1692abc147a889536ba36a7f1e3dbf1762#diff-301b442ddc713ca888197dfd9ebc891cR78

The only one I can see you might not want to apply is the SSH key workaround as you plan to fix that with issue #202. I'm happy to push an update without that workaround if you like. But what you seem to be saying is that none of the rest has any value either. Is that a correct interpretation?

TBH I'm trying to be helpful here and polish up a few rough edges on a project I see as valuable, but by sweeping the whole thing off the table you're leaving me with the impression you don't want the help.

**Comment by dguido** [comment]
Sure, let's see what we can get tomorrow.

**Comment by grempe** [comment]
Glad you were able to make some use of some parts of this PR.

Also I believe it should be 'Google Compute Engine', not 'Google Cloud Engine'

https://cloud.google.com/compute/

Cheers

**Pull request closed without merging**
