### PR TITLE
Refactoring

### LINKED ISSUE #1024: Migrate to python3
https://docs.ansible.com/ansible/2.5/reference_appendices/python_3_support.html
We need to get rid of python2 support.
Ansible 2.5 and above have support for Python 3. Previous to 2.5, the Python 3 support was considered a tech preview.

### LINKED ISSUE #1162: Include option to just set up wireguard
**Describe the solution you'd like**
I'm new to ansible, but it looks as if all of the IKE related code is still running along with the wireguard configuration. I was wondering if it'd be worth it to add an option to just enable wireguard and skip all of the other steps related to IKE, esp given the fact that wireguard has officially been submitted for inclusion into the kernel.

### LINKED ISSUE #1330: Reorganize the project around ipsec + wireguard
We should do some housekeeping on the `config` folder so that relevant files are easier to find. We may also want to rename the `vpn` role to `ipsec` or `strongswan` since it's clear we'll be supporting two VPNs now.

### PR DESCRIPTION
**Pull request by jackivanov**
## Description
Renames the vpn role to strongswan, and split up the variables to support 2 separate VPNs. Closes #1330 and closes #1162
Configures Ansible to use python3 on the server side. Closes #1024 
Removes unneeded playbooks, reorganises a lot of variables
Reorganises the `config` folder. Closes #1330
<details><summary>Here is how the config directory looks like now</summary>
<p>

```
configs/X.X.X.X/
|-- ipsec
|   |-- apple
|   |   |-- desktop.mobileconfig
|   |   |-- laptop.mobileconfig
|   |   `-- phone.mobileconfig
|   |-- manual
|   |   |-- cacert.pem
|   |   |-- desktop.p12
|   |   |-- desktop.ssh.pem
|   |   |-- ipsec_desktop.conf
|   |   |-- ipsec_desktop.secrets
|   |   |-- ipsec_laptop.conf
|   |   |-- ipsec_laptop.secrets
|   |   |-- ipsec_phone.conf
|   |   |-- ipsec_phone.secrets
|   |   |-- laptop.p12
|   |   |-- laptop.ssh.pem
|   |   |-- phone.p12
|   |   `-- phone.ssh.pem
|   `-- windows
|       |-- desktop.ps1
|       |-- laptop.ps1
|       `-- phone.ps1
|-- ssh-tunnel
|   |-- desktop.pem
|   |-- desktop.pub
|   |-- laptop.pem
|   |-- laptop.pub
|   |-- phone.pem
|   |-- phone.pub
|   `-- ssh_config
`-- wireguard
    |-- desktop.conf
    |-- desktop.png
    |-- laptop.conf
    |-- laptop.png
    |-- phone.conf
    `-- phone.png
```

finder

</p>
</details>

## Motivation and Context
This refactoring is focused to aim to the 1.0 release

## How Has This Been Tested?
Deployed to several cloud providers with various options enabled and disabled

## Types of changes

- [x] Refactoring

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by davidemyers** [comment]
I've run the following tests on DigitalOcean with an iOS client and all have passed:

Deploy with IPsec + WG + SSH (OK)
Add a user with `update-users` (OK)
Connect with new user via IPsec (OK)
Connect with new user via WG (OK)

Deploy with WG only (OK)
Connect via WG (OK)
Add a user with `update-users` (OK)
Connect with new user via WG (OK)

The only issue I noticed is that `update-users` on the WG-only instance prompted for the CA key even though there was none.

Also I think the dumping of the invocation environment in `playbooks/cloud-pre.yml` should now include `ipsec_enabled`.

**Comment by akerl** [comment]
I've tested this merged into my fork, using a local Ubuntu 18.04 VM. One thing I noticed is that it still expects the congrats.p12_pass message to be set, even if strongswan_enabled is set to false.

**Comment by TC1977** [comment]
Out of curiosity, why is DNS encryption disabled by default now?

**Comment by ismail** [comment]
I tested this branch with ```ipsec_enabled: false``` and it works as expected but there is one issue, which is minor anyhow is that, iptables still have the ipsec rules:

```
root@algo:~# grep -i ipsec /etc/iptables/rules.v*
/etc/iptables/rules.v4:# Accept IPSEC traffic to ports 500 (IPSEC) and 4500 (MOBIKE aka IKE + NAT traversal)
/etc/iptables/rules.v4:-A INPUT -p ipencap -m policy --dir in --pol ipsec --proto esp -j ACCEPT
/etc/iptables/rules.v4:# Forward any IPSEC traffic from the VPN network
/etc/iptables/rules.v4:-A FORWARD -m conntrack --ctstate NEW -s 10.19.48.0/24 -m policy --pol ipsec --dir in -j ACCEPT
/etc/iptables/rules.v6:# Accept IPSEC traffic to ports 500 (IPSEC) and 4500 (MOBIKE aka IKE + NAT traversal)
/etc/iptables/rules.v6:-A FORWARD -m conntrack --ctstate NEW -s fd9d:bc11:4020::/48 -m policy --pol ipsec --dir in -j ACCEPT
```

Apart from that, works as expected.

**Pull request merged**
