### PR TITLE
use `openssl rand -base64` to generate password

### PR DESCRIPTION
**Pull request by azdkj532**
## Description
Generate password directly by openssl instead of converting by python script.

## Motivation and Context
For python2/python3 compatibility.

## Types of changes
- [v] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [v] I have read the **CONTRIBUTING** document.
- [v] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [] All new and existing tests passed.

### CODE REVIEW

**Comment by azdkj532** [comment]
related to #1573, #1549.

**Comment by jackivanov** [comment]
There was a reason for doing this - https://github.com/trailofbits/algo/pull/657. 

I'm not fan of either ways, and I'd like to move to the native lookup module, something like `{{ lookup('password', '/dev/null length=9 chars=ascii_letters,digits') }}"`

**Comment by azdkj532** [comment]
Agree. The native way is better than this PR.

**Comment by jackivanov** [comment]
You are welcome to send another PR or just the code in this one :)

**Pull request closed without merging**
