### PR TITLE
Amazon ec2 documentation

### PR DESCRIPTION
**Pull request by michael-myers**
Addresses one of the requests in https://github.com/trailofbits/algo/issues/682

Please review for AWS security correctness.

### CODE REVIEW

**Comment by dguido** [comment]
The minimum required AWS policy required for deployment is documented over here: https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md#minimum-required-iam-permissions-for-deployment

You can reduce the privileges of the algovpn IAM account you create by using that policy instead of giving it administrative rights.

**Comment by michael-myers** [comment]
Thanks, I will change the directions and update this branch.

**Comment by michael-myers** [comment]
I think I've updated things to reflect new AWS policy guidance. I noticed that the GitHub markdown web view may not reflect image file replacements immediately.

**Comment by dguido** [comment]
Cool, I think this looks good to me. Reading this reminds me why I encourage people to deploy to DigitalOcean instead :-x.

**Comment by michael-myers** [comment]
Yes, see https://github.com/trailofbits/algo/pull/1095

**Pull request merged**
