### PR TITLE
Created inline policy that limits actions, where supported, to resour…

### PR DESCRIPTION
**Pull request by spankminister**
…ces tagged with Environment:Algo

### CODE REVIEW

**Comment by defunctio** [comment]
Referencing issue #123 as there was a bounty on this issue.

**Comment by dguido** [comment]
How do we "hook this up" to Algo? Is this something we put in the docs, something we use on their API? I'm not very familiar with IAM.

**Comment by defunctio** [comment]
The ACL needs to be tested first but it's usage will just need to be added to advanced usage documentation. It's something the user will need to configure manually on AWS to use.

**Comment by spankminister** [comment]
I noticed the PR has been marked "Needs Testing," should I write the test also? I would just write up a test where I create an instance with a user that has all permissions, then ensure that the Algo user with the inline policy can't modify the untagged VM in any of the ways specified.

I made the policy by running the ansible-playbook command and adding a permission based on the error for which EC2 action failed. When I got the minimum number of permissions for Algo to succeed, I then moved some of those actions and resource constrained them based on the [list of supported APIs on this page](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-supported-iam-actions-resources.html).

**Comment by defunctio** [comment]
It just means that we need to manually test it on our end before we merge it, I just haven't tested it yet.

If you could add documentation and add AWS reference material in the advanced doc section that detail how users can setup IAM users, assign ACL permissions and generate an API key to use with Algo that would also be helpful.

**Comment by aboutte** [comment]
It would also be nice if these two lines of code were updated to reference the new documentation:

https://github.com/trailofbits/algo/blob/master/algo#L222
https://github.com/trailofbits/algo/blob/master/algo#L229

Not only is it not recommended to use the root key and secret it is recommended to NOT generate a key and secret for the root user.  :)

**Comment by defunctio** [comment]
Closing this pull request in favor of #447 for CF support that will be merged soon.

**Pull request closed without merging**
