### PR TITLE
Allow public DNS hostname or IP to be specified on config

### PR DESCRIPTION
**Pull request by darkorigins**
## Description

Quick mod to allow admin to specify server public hostname or ip address in ./algo config

## Motivation and Context

Removes reliance on IP address of server allowing server to be moved/clustered

## How Has This Been Tested?

Works here :-)

## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by darkorigins** [comment]
I've labelled this as "Breaking change" just in case the IP was used as an IP rather than hostname elsewhere.  I can't see any but ..

**Comment by davidemyers** [comment]
Were commits 3b5cb54 and 2c88b5c intended for this PR?

I'm not a GitHub guru, but you probably wanted to submit the original PR from a branch other than `master` so any subsequent pushes to `master` don't end up in the PR.

**Comment by darkorigins** [comment]
Yup, sorry, they where pushed to our fork.  Didn't realise you'd see them as well.

Also not a GitHub guru :-)  I'd assume you'd only see the commit I sent you.

Sorry, please ignore them.

**Comment by jackivanov** [comment]
Please, rebase it

**Comment by darkorigins** [comment]
Hi

Better?

That should be the two extra commits removed.

**Comment by jackivanov** [comment]
Yes, the checklist should be updated as well (in the first message). Also, I'm not a fan of adding more dependencies (netaddr), but as far as I know it's a plugin, not module and there is no way to load plugins during the playbook execution. Any thoughts from anyone?

**Comment by darkorigins** [comment]
I agree with the hesitation on dependancy, I had the same one. Although it felt neater than adding regex's for IPv4 & all the IPv6 forms

**Comment by jackivanov** [comment]
I think so. We need to update CHANGELOG.md as well to let users know they need to rebuild requirements.

**Comment by digeratus** [comment]
Is there any way I can help test this to get it committed? Thanks

**Comment by jackivanov** [comment]
Closing in favor of #1337

**Pull request closed without merging**
