### PR TITLE
Consolidate firewall documentation

### PR DESCRIPTION
**Pull request by davidemyers**
## Description

Created a new document to describe in some detail how Algo uses firewalls.

## Motivation and Context

Users often have questions about firewalls, especially those doing local installs, so putting the information in a single document should be helpful.

## How Has This Been Tested?

Made sure all the links work correctly.

## Types of changes

- [x] Documentation

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by davidemyers** [comment]
@TC1977 Please review.

**Comment by TC1977** [comment]
I think this looks great. Only thing that I'd add in the firewall.md doc itself, in the section 'Server Firewall', would be a mention that Algo configures ip6tables as well as iptables, when ipv6 support is enabled.

**Comment by davidemyers** [comment]
@TC1977 Thanks for the review. I've added a note about IPv6 rules.

**Comment by kamalalnabrissi2** [comment]
Y

**Pull request merged**
