### PR TITLE
Simplify Apple Profile Configuration Template

### PR DESCRIPTION
**Pull request by faf0**
Fix indentation of template statements, remove empty else-clauses, and remove blank newlines.

### CODE REVIEW

**Comment by jackivanov** [comment]
Will be reviewed after https://github.com/trailofbits/algo/pull/976

**Comment by davidemyers** [comment]
Doesn't adding extra spaces in the template cause unnecessary spaces to be left in the generated file?

**Comment by faf0** [comment]
@davidemyers You are right. There are actually already blank lines in the files generated by the code from master. I updated this PR to remove blank lines as well.

**Comment by jackivanov** [comment]
I'm pretty sure it breaks indentation now, although it doesn't make it unusable, but makes it unreadable.  Probably you can use lstrip_blocks

**Comment by faf0** [comment]
@jackivanov Your assessment is correct. I enabled lstrip_blocks.

**Comment by jackivanov** [comment]
@faf0 Could you, please, rebase from the master? We are going to merge this in 1.1

**Comment by faf0** [comment]
@jackivanov rebased from master

**Comment by jackivanov** [comment]
Thanks!

**Pull request merged**
