### PR TITLE
Ubuntu 22.04 support

### PR DESCRIPTION
**Pull request by jackivanov**
## Motivation and Context
Support latest Ubuntu LTS release

## How Has This Been Tested?
Deployed to digitalocean

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ar1hur** [comment]
tested on hetzner cloud - it works!

**Comment by pentest01** [comment]
How do i merge this to my forked repo. I'm new to git please and i need help, i've googled but haven't seen any useful result.

**Comment by MGelbana-Incorta** [comment]
How was this tested on digital ocean? I installed it using the `./algo` command but it didn't work for me.

**Comment by MGelbana** [comment]
How was this tested on digital ocean? I installed it using the ./algo command but it didn't work for me.

**Pull request merged**
