### PR TITLE
Update config.cfg

### PR DESCRIPTION
**Pull request by TC1977**
Reflects fixes in #1434 and #1435.

## Description

Keeping docs up to date.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [] I have read the **CONTRIBUTING** document.
- [] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [] All new and existing tests passed.

### CODE REVIEW

**Comment by jackivanov** [comment]
The note about escaping in [this line](https://github.com/trailofbits/algo/blob/master/config.cfg#L11) and I just updated it :)

**Comment by jackivanov** [comment]
Perhaps we may move it above the variable, as you suggested?

**Comment by TC1977** [comment]
That's how all the other notes are. Should I rebase or just close this?

**Comment by jackivanov** [comment]
Yes, please, rebase

**Comment by TC1977** [comment]
Actually it looks like rebase wasn't needed, because I put my PR in right after you changed it. I've just updated it.

**Pull request merged**
