### PR TITLE
Swapping out the plain dnscrypt-proxy binary instead of the PPA repo (#1682)

### PR DESCRIPTION
**Pull request by rodeodomino**
## Description
This change removes the PPA installation of dnscrypt-proxy for Ubuntu installations (#1682) and updates the conf file to work with its changes. It also adds the update code as [seen on the dnscrypt-proxy github page](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Updates).

## Motivation and Context
The old PPA repo is outdated and adds an unnecessary systemd socket.

## How Has This Been Tested?
Deployed on Digital Ocean

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [X] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by davidemyers** [comment]
AppArmor is not being enforced. I think the config file has to start with:
```
/opt/dnscrypt-proxy/dnscrypt-proxy flags=(attach_disconnected) {
```

**Comment by davidemyers** [comment]
With this change `dnscrypt-proxy` now runs as `root`. I'm not sure if this is a cause for concern.

**Comment by rodeodomino** [comment]
> AppArmor is not being enforced. I think the config file has to start with:
> 
> ```
> /opt/dnscrypt-proxy/dnscrypt-proxy flags=(attach_disconnected) {
> ```

Adjusted in the pull request. I'm not great with app armor, though, so hopefully I haven't broken anything there.

**Comment by rodeodomino** [comment]
Unfortunately, I've hit the end of my apparmor experience.

Currently, when installing it throws an error ` \"systemctl\" failed: fork/exec /bin/systemctl: permission denied`. It feels weird to add systemctl to this apparmor profile, but could keep trying. The only other solution I have is to turn off apparmor for this since it's only in the GO binary?

**Comment by jackivanov** [comment]
We have to include properly configured apparmor profile

**Comment by rodeodomino** [comment]
Thanks @jackivanov -- would you like me to close the pull request? Apparmor is beyond my skills. Oh well!

**Comment by jackivanov** [comment]
Thanks @rodeodomino, I'll take a look

**Comment by kfken** [comment]
Realize this is closed, but my guess is that it's running as non-root because of /lib/systemd/system/dnscrypt-proxy.service, (which is probably created by the ppa package):

`
DynamicUser=yes
`

One possible way to address this is modify dnscrypt-proxy.toml and set "user_name = nobody" or similar.

**Pull request closed without merging**
