### PR TITLE
Improvements to the compatible cipher suite

### LINKED ISSUE #462: Invalid payload received when connecting from Windows 10
### OS / Environment

Windows 10 Build 15063.138

### Summary of the problem
VPN connection from Windows 10 results in "Invalid payload received" error for both Azure and AWS on commit b94b455aba081e3fc4d35378253e61b9c01c3243. Older version of Algo (commit a5ea5d8bb5ffba78293224bd1f3e4af3fc92d378 from April 13 EST) didn't have this problem.

### Steps to reproduce the behavior
Set up Algo fresh on a new provider following the instructions. Connect from a windows 10 machine. (Mac and iOS works just fine with the mobileconfig)

### The way of deployment (cloud or local)
cloud

### Expected behavior
Be able to connect on windows 10

### Actual behavior
Not be able to connect on windows 10

### PR DESCRIPTION
**Pull request by gunph1ld**
Fixes #462 and adds some enhancements mentioned in #9.

### CODE REVIEW

**Comment by dguido** [comment]
Nice! We got AES-GCM working on Windows!

But I don't we can remove modp2048 yet. That is Group14 which we still reference in the Powershell script.

**Comment by dguido** [comment]
It looks like we can specify ECP256!

https://technet.microsoft.com/en-us/library/dn262642(v=wps.630).aspx

**Comment by gunph1ld** [comment]
Yep, It's possible to use DH group 19 on Windows, but I was not able to connect with those changes

**Comment by dguido** [comment]
It looks like we can also raise the IntegrityCheckMethod to SHA384

**Comment by gunph1ld** [comment]
DH Group 19 and ECDSA certificates are implemented, I don't think there is a way to use AES-GCM 128 and SHA2-512 PRF

**Comment by dguido** [comment]
```
-AuthenticationTransformConstants GCMAES128
-CipherTransformConstants GCMAES128
-DHGroup ECP256
-EncryptionMethod AES128
-IntegrityCheckMethod SHA384
```
I think the corresponding IKE line from ipsec.conf for the above looks like:

```
aes128gcm16-prfsha512-ecp256 # Default
aes128gcm16-prfsha384-ecp256 # Windows
aes128-sha2_512-prfsha512-ecp256 # Network Manager 1.4.1
```

I'm not sure the PfsGroup setting is required? PFS should come for "free" if we use AES-GCM, right? What does the strongswan log report when you change that setting back and forth to different values?

**Comment by gunph1ld** [comment]
> I think the settings we want in PowerShell are:
Yes, these values already in the PR
And Windows proposes this: `IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256`

**Comment by dguido** [comment]
I guess we may as well set the PfsGroup parameter to "ECP256"

**Comment by gunph1ld** [comment]
Sorry, I made a copy-paste mistake. window propose other algorithms, see my edited message above

**Comment by dguido** [comment]
Weird... why won't it turn on AES-GCM???

**Comment by gunph1ld** [comment]
It turns on for the esp

**Comment by dguido** [comment]
Ohhhh, so strange. Can you do some testing with the PfsGroup parameter to see what it does? Once we get a better understanding of how that modifies things, then we can accept this PR.

**Comment by gunph1ld** [comment]
nothing changes with `-PfsGroup ECP256`

```
IKE:AES_CBC_128/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/ECP_256
ESP:AES_GCM_16_128/NO_EXT_SEQ
```

**Comment by jauderho** [comment]
Has anyone checked what happens when you switch from aes128gcm8, aes128gcm12 or aes128gcm16?

**Comment by dguido** [comment]
No, those don't assist with compatibility. Also, you are advised to avoid them due to shorter IV lengths.

**Comment by bshiznit** [comment]
Hey all - over in #354 I noted and have continued testing Windows 10 with:
`Set-VpnConnectionIPsecConfiguration -ConnectionName "<NAME>" -AuthenticationTransformConstants GCMAES128 -CipherTransformConstants GCMAES128 -EncryptionMethod AES128 -IntegrityCheckMethod SHA384 -DHGroup ECP256 -PfsGroup ECP256`

Switching -PfsGroup from None to ECP256. This has helped with the hourly rekeying connection tunnel Win10 issues so I will send a PR.

**Pull request merged**
