### PR TITLE
Enhance PS1 script

### LINKED ISSUE #454: Windows: Ability to undo/reverse everything
For now, that is a relatively easy way to add VPN. But to remove VPN plus all the CA Cert is bit more complicated. (At least for me)

So I wonder if we should add a powershell script that does exactly the opposite of the currently-implemented ps1.

P.S. Is there a easier way to run ps1 without run command first.

### PR DESCRIPTION
**Pull request by gunph1ld**
Fixes #454

### CODE REVIEW

**Comment by dguido** [comment]
Neat! Needs docs.

**Comment by tony199555** [comment]
Looks great. Thank you for your work.

**Comment by tony199555** [comment]
I will try do some test today, but I do need some docs for more specific actions too. If you could provide some instruction that would be great.

**Comment by gunph1ld** [comment]
> Do I still need to add CA before running this script?

No, you don't

> Do you see we can do something about it, too?

Just run the script as Administrator, it works for me and adds the CA itself

**Comment by gunph1ld** [comment]
added some new docs

**Pull request merged**
