### PR TITLE
on-build python venvs

### PR DESCRIPTION
**Pull request by jackivanov**
## Description
This PR moves all the python libraries to the particular roles and leaves only Ansible in the requirements, all other required libraries will be installed by Algo itself to the appropriate paths. It helps to update libraries, make new tasks and delete old ones without forcing users to run _pip install_ each time we change the requirements.txt

## Motivation and Context
The main goal is to let users start with Algo more simpler. 

## How Has This Been Tested?
As for now, we need to do more tests and make sure everything worked smoothly and as expected

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

## Tests

- [x] DigitalOcean
- [x] Amazon Lightsail
- [x] Amazon EC2
- [x] Vultr
- [x] Microsoft Azure
- [x] Google Compute Engine
- [x] Scaleway
- [x] OpenStack (DreamCompute optimised)
- [x] Install to existing Ubuntu 18.04 server (Advanced)
- [x] Deploy from Docker

### CODE REVIEW

**Comment by TC1977** [comment]
local install option onto Ubuntu 18.04 AWS EC2 instance worked for me.

```ssh
Algo running on: Ubuntu 18.04.1 LTS (Virtualized: xen)
Created from git fork. Last commit: c603980 lightsail venv fix
Python 2.7.15rc1
Runtime variables:
    algo_provider "local"
    algo_ondemand_cellular "False"
    algo_ondemand_wifi "False"
    algo_ondemand_wifi_exclude "_null"
    algo_local_dns "True"
    algo_ssh_tunneling "True"
    algo_windows "False"
    wireguard_enabled "True"
    dns_encryption "True"
```
...
```ssh
ok: [localhost] => {
    "msg": [
        [
            "\"#                          Congratulations!                            #\"", 
            "\"#                     Your Algo server is running.                     #\"", 
            "\"#    Config files and certificates are in the ./configs/ directory.    #\"", 
            "\"#              Go to https://whoer.net/ after connecting               #\"", 
            "\"#        and ensure that all your traffic passes through the VPN.      #\"", 
            "\"#                     Local DNS resolver 172.16.0.1                    #\"", 
            ""
        ], 
        "    \"#        The p12 and SSH keys password for new users is xxxxxxxx       #\"\n", 
        "    \"#        The CA key password is xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       #\"\n", 
        "    "
    ]
}
```
Dnscrypt-proxy, Wireguard, and dnsmasq are up and running, and Web browsing works fine.

**Comment by davidemyers** [comment]
I've been reluctant to try Vultr because of their billing terms, but I gave in.
```\Algo running on: Ubuntu 18.04.1 LTS
Created from git clone. Last commit: c603980 lightsail venv fix
Python 2.7.15rc1
Runtime variables:
    algo_provider "vultr"
    algo_ondemand_cellular "True"
    algo_ondemand_wifi "True"
    algo_ondemand_wifi_exclude "_null"
    algo_local_dns "False"
    algo_ssh_tunneling "False"
    algo_windows "False"
    wireguard_enabled "True"
    dns_encryption "True"
```
Same result as my DO deploy above.

**Comment by davidemyers** [comment]
Re-deployed to DO and WireGuard IPv6 works.

**Comment by jackivanov** [comment]
Scaleway and OpenStack also work

**Comment by jackivanov** [comment]
Installation via Docker is probably broken 

- [ ] check docker

**Comment by davidemyers** [comment]
Just noticed a small typo copied and pasted into the various `main.yml` files:
```
- name: Buld python virtual environment
```
Buld -> Build

**Comment by RyanBalfanz** [comment]
> I've been reluctant to try Vultr because of their billing terms, but I gave in.

Why were you reluctant?

**Comment by davidemyers** [comment]
According to the Vultr [Terms of Service](https://www.vultr.com/legal/tos/), they bill you in advance for services, give you no easy way to cancel, and won't refund any unused balance. Other providers bill you for services you've actually used.

Some excerpts:

> Payment for Services is due in advance of the time period for which such payment covers. Services are billed on an automatic and recurring basis unless and until you follow Vultr's cancellation procedure set forth in this Agreement.


There is no cancellation procedure set forth in the agreement, though there's a reference to a "cancellation form".

> If you cancel any Service prior to the expiration of the pre-paid Fees, You understand and agree that Vultr will not issue You any refund whatsoever, including but not limited to any remaining pre-paid Fees, set up Fees, and/or special programming Fees.

**Pull request merged**
