### PR TITLE
Update local install instructions

### PR DESCRIPTION
**Pull request by davidemyers**
## Description

Simplified the local installation instructions.

## Motivation and Context

The instructions appeared to be out-of-date, as mentioned in #1145. No special steps appear to be necessary to do a local install.

## How Has This Been Tested?

Deployed to a local server using the changes in #1147. Others might wish to test this as well.

Did not test the option to skip `iptables`, just carried the instructions forward.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by TC1977** [comment]
@davidemyers _Deleting_ the local install instructions wasn't what I had in mind. 😅 

Using the usual install instructions (i.e., 
```
git clone https://github.com/trailofbits/algo		
cd algo
sudo apt-get update && sudo apt-get install \
    build-essential \
    libssl-dev \
    libffi-dev \
    python-dev \
    python-pip \
    python-setuptools \
    python-virtualenv -y
python -m virtualenv --python=`which python2` env &&
    source env/bin/activate &&
    python -m pip install -U pip &&
    python -m pip install -r requirements.txt
```
on an AWS Ubuntu 18.04 instance fails with the following:

```ssh

TASK [vpn : Create links for the private keys] ***************************************************************************
failed: [localhost -> localhost] (item=dan) => {"changed": false, "item": "dan", "msg": "the python pyOpenSSL module is required"}
failed: [localhost -> localhost] (item=jack) => {"changed": false, "item": "jack", "msg": "the python pyOpenSSL module is required"}

```

**Comment by TC1977** [comment]
Okay, here's something weird. The iptables rules weren't overwritten.

```ssh
ubuntu@ip-172-31-35-19:~/algo$ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```

**Comment by TC1977** [comment]
> My thinking was that duplicating the instructions will just lead to maintenance headaches when both sets have to be updated in lockstep.

How about at the very least, just explicitly instructing `git clone https://github.com/trailofbits/algo` and `cd algo`, then a [link back to the readme](https://github.com/trailofbits/algo/commits/master/README.md) for the base instructions?

> Also, the local install prompt says "Advanced", which I interpret as meaning inexperienced users should probably not try it.

True, but when has that stopped anyone? And even experienced users appreciate cut-and-paste. 😄

**Comment by TC1977** [comment]
Doesn't have to be `git clone https://github.com/trailofbits/algo`, I suppose, but _some_ explicit instructions we can simply cut and paste would be nice. Every other page in the docs has them.

**Comment by davidemyers** [comment]
Can Dan or Jack cast a tie-breaking vote? :smile:

I don't mind duplicating the instructions here, my concern is that will make this page more likely to become incorrect whenever the instructions in the README are updated, like it is now.

**Comment by davidemyers** [comment]
Here's what I would add:

----
Here is an Ubuntu-specific summary of the commands to run to perform a local deployment. For a local deployment, Algo is installed and run on the Ubuntu Server instance that is to become a VPN server, whereas with a cloud deployment Algo is installed and run on a separate system. Also, for a local deployment you'll probably want to run all of these commands as `root`.

Install the prerequisite system packages:
```shell
sudo apt update && sudo apt install \
    build-essential \
    libssl-dev \
    libffi-dev \
    python-dev \
    python-pip \
    python-setuptools \
    python-virtualenv -y
```
Since `unzip` is not installed by default it's easier to clone the GitHub repository than download the ZIP file:
```shell
git clone https://github.com/trailofbits/algo 
cd algo
```
Install the remaining packages in a Python virtual environment and activate the environment:
```shell
python -m virtualenv --python=`which python2` env &&
    source env/bin/activate &&
    python -m pip install -U pip &&
    python -m pip install -r requirements.txt
```
Edit the file `config.cfg` with `vi` or `nano` to add users and then run Algo:
```shell
vi config.cfg
./algo
```

**Comment by jackivanov** [comment]
I don't think we need this page at all (deploy-to-ubuntu.md). There are instruction in the main readme already. And as David said, duplicating the instructions will just lead to maintenance headaches

**Comment by davidemyers** [comment]
I think a warning that a local install assumes a dedicated system (and will stomp on existing firewall rules) will head off some user issues, but it doesn't have to be on this page.

**Comment by TC1977** [comment]
@jackivanov The first line of the main readme instructions ("The easiest way to get an Algo server running is to let it set up a new virtual machine in the cloud for you. ") implies a cloud install. [Cloud install from Windows](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-windows.md) and [local deploy to FreeBSD](https://github.com/trailofbits/algo/blob/master/docs/deploy-to-freebsd.md) each get their own page. The local deploy to Ubuntu option seems to have more people using it, or at least getting more problems with it, judging by the number of issues filed (#1145, #1139, #1133, #1119, #1118 just from the last month). Deleting the local deploy page entirely won't keep people from running into problems, unless you promote the instructions to the main readme page (where it probably doesn't belong). 

If duplicating the explicit instructions leads to headaches, you could always just link back to the main readme.

**Comment by dguido** [comment]
I guess all the virtualenv stuff and recent refactoring eliminates the need for this page? I think I'm with Jack, let's just deprecate this page entirely if it's not needed.

**Comment by davidemyers** [comment]
I think leaving the page could be helpful because there seem to be recurring issues where the user wants to use their server for multiple purposes and then goes and messes up the firewall. There are also users who want to use their server for local network ingress and this page could either contain tips for doing that or could discourage the practice altogether.

**Comment by dguido** [comment]
Ok we'll leave it for now.

**Pull request merged**
