### PR TITLE
add info to README about escaping usernames

### PR DESCRIPTION
**Pull request by lgg**
It wasn't obvious for users how to escape nicknames and was it needed at all

see #246 for more

### CODE REVIEW

**Comment by dguido** [comment]
Hmm maybe we can explain this more concisely? It's very verbose considering the small number of users likely to make usernames with leading 0's.

**Comment by dguido** [comment]
I think we can just say "(avoid usernames with leading 0's)" in parenthesis without explaining why when asking people to pick usernames.

**Comment by lgg** [comment]
@dguido why users need to avoid them if they still can use them? 

In my case usernames with zeros exist because of SIP. (it's easier to tell digits instead of letters) And we have one system for all (in all services usernames and passwords are same).

**Comment by jamesbroadhead** [comment]
Would this be better as a comment in the yaml file?

**Comment by dguido** [comment]
If you want to make a discrete little comment on the yaml file, submit a PR please!

**Pull request closed without merging**
