### PR TITLE
AGPLv3 change

### PR DESCRIPTION
**Pull request by dguido**

### CODE REVIEW

**Comment by akerl** [comment]
How does this work given prior contributions, which were provided under the MIT license?

**Comment by andreimc** [comment]
you can use anything prior under MIT license

**Comment by akerl** [comment]
@andreimc , to clarify, my point is that for people who haven’t assigned ownership of their code to trailofbits (via the new CLA), their past contributions still exist under MIT, they can’t just be relicensed without their consent.

**Comment by dguido** [comment]
Thanks, we did a review and there are only a small handful of non-CLA contributions in all of Algo’s prior development. Further, most of that code has been overwritten by CLA contributed code or deleted. If you feel that I made an error, I’ll be happy to mark down any non-CLA code in a text file somewhere and identify it separately as MIT.

**Pull request merged**
