### PR TITLE
cleaner syntax for local actions

### PR DESCRIPTION
**Pull request by rvben**
Good evening! :)

The use of the 'local_action' module is often less clean, as it makes code look very different, while the only thing that you want different is the host on which it runs. It's therefore cleaner to use "delegate_to: localhost", which can also be used on a higher level (includes/blocks) to make it even cleaner.

What do you think?

### CODE REVIEW

**Comment by gunph1ld** [comment]
Great, Thanks. Can you make all the openssl commands multiline?

**Comment by rvben** [comment]
Sure, that definitely makes it better. I made the changes.

**Comment by rvben** [comment]
Of course. It's now rebased. :)

**Comment by rvben** [comment]
Added #544 to this PR.

**Pull request merged**
