### PR TITLE
Ubuntu 20.04 support

### PR DESCRIPTION
**Pull request by jackivanov**
## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by davidemyers** [comment]
Don't forget the prompt in [input.yml](https://github.com/trailofbits/algo/blob/e8606a61185de9ae8a180e6588249415860b0b19/input.yml#L24).

**Comment by jackivanov** [comment]
@davidemyers Ok, seems done, can you take a look?

**Comment by davidemyers** [comment]
Deployed to DigitalOcean and confirmed that the WireGuard module bundled with the kernel is being used and `dkms` is no longer installed.

In my recent PR in `roles/strongswan/defaults/main.yml` I tested the OS version with `ansible_distribution_major_version|int > 19`. In this PR you use the more elegant `version('20.04', '<')`. Do you want to change what I did previously to `version('20.04', '>=')`?

**Comment by jackivanov** [comment]
@davidemyers good catch, thanks, added

**Pull request merged**
