### PR TITLE
Monitoring: Add go-audit

### PR DESCRIPTION
**Pull request by tho**
Partial solution for #16.

This PR only addresses the installation and configuration of go-audit on Ubuntu 16.04. It does not implement any processing of audit events or user notifications. I am happy to look into adding these parts as well but wonder what the best course of action would be. In particular:

1. Should a minimal MTA (postfix?) which directly delivers mails be configured?

2. Should something like http://msmtp.sourceforge.net/ be configured?

3. Should the JSON output of go-audit be converted to a more user friendly format?

    FYR sample event:

        {
          "sequence": 253,
          "timestamp": "1514597820.465",
          "messages": [
            {
              "type": 1300,
              "data": "arch=c000003e syscall=2 success=yes exit=8 a0=7fd6fd5394d0 a1=80002 a =7fd6fd535e32 a3=76d items=1 ppid=9016 pid=9020 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts1 ses=5 comm=\"sshd\" exe=\"/usr/sbin/sshd\" key=\"session\""
            },
            {
              "type": 1307,
              "data": " cwd=\"/\""
            },
            {
              "type": 1302,
              "data": "item=0 name=\"/var/run/utmp\" inode=410 dev=00:13 mode=0100664 ouid=0 ogid=43 rdev=00:00 nametype=NORMAL"
            },
            {
              "type": 1327,
              "data": "proctitle=737368643A20726F6F74407074732F31"
            }
          ],
          "uid_map": {
            "0": "root"
          }
        }

Therefore, I do not expect this PR to get merged as-is.

## Testing Done

    $ cd roles/go_audit/tests
    $ vagrant up
    $ vagrant snapshot save init

### Role testing

    #
    # Build go-audit from source
    #
    $ ansible-playbook -i ./inventory test.yml -v
    PLAY RECAP *********************************************************************
    ubuntu16.04-386            : ok=22   changed=17   unreachable=0    failed=0   
    ubuntu16.04-amd64          : ok=22   changed=17   unreachable=0    failed=0   
    $ ansible-playbook -i ./inventory test.yml -v
    PLAY RECAP *********************************************************************
    ubuntu16.04-386            : ok=18   changed=0    unreachable=0    failed=0   
    ubuntu16.04-amd64          : ok=18   changed=0    unreachable=0    failed=0   

    $ vagrant snapshot restore init

    #
    # Use pre-built binaries 
    #
    $ ansible-playbook -i ./inventory test.yml -e"go_audit_build=no" -v
    PLAY RECAP *********************************************************************
    ubuntu16.04-386            : ok=14   changed=10   unreachable=0    failed=0   
    ubuntu16.04-amd64          : ok=14   changed=10   unreachable=0    failed=0  
    $ ansible-playbook -i ./inventory test.yml -e"go_audit_build=no" -v
    PLAY RECAP *********************************************************************
    ubuntu16.04-386            : ok=12   changed=0    unreachable=0    failed=0   
    ubuntu16.04-amd64          : ok=12   changed=0    unreachable=0    failed=0   

### Integration testing

    #
    # Local deployment
    #
    $ vagrant ssh ubuntu16.04-amd64
    ubuntu@ubuntu-xenial:/vagrant_algo$  # command generated by ./algo
        ansible-playbook deploy.yml \
	    -t local,vpn,security,monitoring \
	    -e "server_ip=localhost server_user=root IP_subject_alt_name=192.168.55.64
            Store_CAKEY=N --skip-tags _null,encrypted,cloud,update-alternatives"

    # If a reboot of the VM is required it might be necessary to run
    # `vagrant reload` before re-running the above command in order to
    # setup the vagrant_algo synced folder.

    ubuntu@ubuntu-xenial:/vagrant_algo$
        ansible-playbook deploy.yml \
	    -t local,vpn,security,monitoring \
	    -e "server_ip=localhost server_user=root IP_subject_alt_name=192.168.55.64
            Store_CAKEY=N --skip-tags _null,encrypted,cloud,update-alternatives"
    PLAY RECAP *******************************************************************
    localhost                  : ok=111  changed=80   unreachable=0    failed=0

    #
    # Clould deployment on DigitalOcean
    #
    $ ./algo
    [ ... ]
    Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
    [y/N]: n
    Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
    [y/N]: y
    Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
    [y/N]: n
    Do you want each user to have their own account for SSH tunneling?
    [y/N]: n
    Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
    [y/N]: y
    Do you want to enable security monitoring? (requires configuration in config.cfg)
    [y/N]: y
    Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
    [y/N]: n
    Do you want to retain the CA key? (required to add users in the future, but less secure)
    [y/N]: n
    PLAY RECAP
    *********************************************************************
    XXX.XXX.XXX.XXX            : ok=106  changed=83   unreachable=0    failed=0
    localhost                  : ok=19   changed=8    unreachable=0    failed=0

    I applied the generated iOS profile and was able to use the VPN.

### CODE REVIEW

**Comment by dguido** [comment]
Thank youuuuuuuu

**Comment by benturner** [comment]
@tho are you still working on this? I'd love to see this get integrated.

**Comment by tho** [comment]
> @tho are you still working on this? I'd love to see this get integrated.

Admittedly I forgot about this PR. I will pick it up again and rebase.
Sorry for keeping the PR dangling & thanks for bringing it to my attention!

**Comment by benturner** [comment]
Hi @tho, bumping this again :)

**Comment by tho** [comment]
Sorry for the long delay!

Aside from rebasing onto master I have made the following changes:

-  Only support Ubuntu 18.04 64 bit. Is 32 bit support required?
-  Bump go and go-audit versions
-  Refactor to follow algo's Ansible conventions more closely

The role by itself is not very useful (yet?), primarily because it lacks good reporting / notification of users. Nevertheless, I hope it can be used as a building block to add auditing to algo. I would appreciate feedback and please let me know how you want to proceed.

Thanks!

**Pull request closed without merging**
