### PR TITLE
remove extraneous integrity algos from AEAD ciphers

### PR DESCRIPTION
**Pull request by dguido**
In reference to
https://github.com/trailofbits/algo/issues/9#issuecomment-294370560

### CODE REVIEW

**Comment by dguido** [comment]
I tested this with iOS and macOS and everything works as expected.

```
ikev2-pubkey[2]: ESTABLISHED 19 seconds ago, 104.236.14.152[104.236.14.152]...72.89.32.203[dan]
ikev2-pubkey[2]: IKEv2 SPIs: 845b5013c37f7de5_i 498c316fd00ef7a5_r*, rekeying disabled
ikev2-pubkey[2]: IKE proposal: AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256
ikev2-pubkey{2}:  INSTALLED, TUNNEL, reqid 2, ESP in UDP SPIs: ce711e91_i 0e7aa78d_o
ikev2-pubkey{2}:  AES_GCM_16_128, 1062 bytes_i (17 pkts, 17s ago), 2097 bytes_o (14 pkts, 17s ago), rekeying disabled
ikev2-pubkey{2}:   0.0.0.0/0 ::/0 === 10.19.48.2/32 fd9d:bc11:4020::2/128
ikev2-pubkey[1]: ESTABLISHED 70 seconds ago, 104.236.14.152[104.236.14.152]...72.89.32.203[dan]
ikev2-pubkey[1]: IKEv2 SPIs: c27e20e6ab671d3c_i 5f227a09a7b8950d_r*, rekeying disabled
ikev2-pubkey[1]: IKE proposal: AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256
ikev2-pubkey{1}:  INSTALLED, TUNNEL, reqid 1, ESP in UDP SPIs: cf94ac2e_i 04ebd380_o
ikev2-pubkey{1}:  AES_GCM_16_128, 140303 bytes_i (663 pkts, 1s ago), 199353 bytes_o (508 pkts, 1s ago), rekeying disabled
ikev2-pubkey{1}:   0.0.0.0/0 ::/0 === 10.19.48.1/32 fd9d:bc11:4020::1/128
```

However, I tried removing the extraneous IntegrityAlgorithm SHA2-512 from the mobileconfig and it breaks. I'm not sure why that would happen. If you open up the profile in Configurator, it even greys out the IntegrityAlgorithm selection box when AES-GCM is selected. This implies that part of the profile would be skipped since it is an authenticated cipher mode.

```
                    <key>IntegrityAlgorithm</key>
                    <string>SHA2-512</string>
```

**Comment by dguido** [comment]
Oh that's odd. It looks like the IntegrityAlgorithm selection in the mobileconfig also controls what PRF iOS and macOS will advertise. Here's what happens if you choose AES-GCM but don't specify the optional IntegrityAlgorithm in a mobileconfig:

```
05[IKE] IKE_SA (unnamed)[2] state change: CREATED => CONNECTING
05[CFG] selecting proposal:
05[CFG]   no acceptable PSEUDO_RANDOM_FUNCTION found
05[CFG] received proposals: IKE:AES_GCM_16_128/PRF_HMAC_SHA1/ECP_256
05[CFG] configured proposals: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256
05[IKE] remote host is behind NAT
05[IKE] received proposals inacceptable
```

I guess we should just leave it as is.

**Comment by jauderho** [comment]
BTW I don't think you wanted to add the prf in `aes128-sha2_512-prfsha512-modp2048` for the following line since the prior cipher does not have it spelt out.

esp: aes128gcm16-ecp256,aes128-sha2_512-ecp256,aes128-sha2_512-prfsha512-modp2048!

**Comment by dguido** [comment]
oh ffs I missed that

**Comment by jauderho** [comment]
LOL

**Pull request merged**
